import = [
    "~/.config/alacritty/themes/themes/ubuntu.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10


decorations = "Buttonless"
opacity = 0.95
blur = false

[font]
normal = { family = "SauceCodePro Nerd Font", style = "SemiBold" }
size = 12
builtin_box_drawing = true

